### ISSUE TITLE
Unable to run setup.sh w/o error

### ISSUE THREAD

**Issue by mhatle** [WindRiver-OpenSourceLabs/wrlinux-x#1]
When running setup, a python traceback occurs..

Searching for git-repo...
Loading the mirror index from git://github.com/WindRiver-OpenSourceLabs/mirror-index (master-wr)...
ERROR: Traceback (most recent call last):
ERROR:   File "/.../wrlinux-x/bin/setup.py", line 1245, in <module>
ERROR:     
ERROR: x.main(sys.argv)
ERROR:   File "/.../wrlinux-x/bin/setup.py", line 174, in main
ERROR:     
ERROR: self.load_layer_index()
ERROR:   File "/.../wrlinux-x/bin/setup.py", line 364, in load_layer_index
ERROR:     
ERROR: self.index = Layer_Index(indexcfg=settings.INDEXES, base_branch=self.base_branch, replace=replace, mirror=mirror_index_path)
ERROR:   File "/.../wrlinux-x/bin/layer_index.py", line 49, in __init__
ERROR:     
ERROR: pindex = self.load_serialized_index(os.path.join(dirpath, filename), name='Mirrored Index')
ERROR:   File "/.../wrlinux-x/bin/layer_index.py", line 364, in load_serialized_index
ERROR:     
ERROR: loadCache(path)
ERROR:   File "/.../wrlinux-x/bin/layer_index.py", line 335, in loadCache
ERROR:     
ERROR: pindex = json.load(open(path, 'rt', encoding='utf-8'))
ERROR:   File "/usr/lib64/python3.4/json/__init__.py", line 268, in load
ERROR:     
ERROR: parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
ERROR:   File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
ERROR:     
ERROR: return _default_decoder.decode(s)
ERROR:   File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
ERROR:     
ERROR: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
ERROR:   File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
ERROR:     
ERROR: raise ValueError(errmsg("Expecting value", s, err.value)) from None
ERROR: ValueError
ERROR: : 
ERROR: Expecting value: line 1 column 1 (char 0)

**Comment by mhatle** [comment]
The issue was caused by a recent change to add README and License information to the mirror-index.  Working on a solution.

**Comment by mhatle** [comment]
Fixed:  https://github.com/WindRiver-OpenSourceLabs/wrlinux-x/commit/2ca1a0de7ac64583ae46bcd07f4059dcbfec96d3
